### ISSUE TITLE
Loading photos in upload queue

### ISSUE THREAD

**Issue by kylebolstad** [Goyaka/Flickr2Facebook#1] opened 2012-07-11 07:33 UTC
I forked the repo and am running it on Engine Yard Cloud / MongoHQ. It successfully connected to both Facebook and Flickr. I selected one photoset. I see it trying to start, but it is stuck on "Loading photos in upload queue".

**Comment by Sriram137** [comment] 2012-08-07 10:32
Hey, the issue is fixed now. Pull from master and run the following runners

rails r Worker.beanstalk_pusher
rails r Worker.create_fb_albums
rails r Worker.split_sets_loop
rails r Worker.upload_loop_batch

**Closed as completed by Sriram137** 2012-08-07 10:32 UTC
